
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 28 00:05:34 CST 2022
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEI = 21;
  public static final int CORCHETEF = 22;
  public static final int PUNTO = 16;
  public static final int INTERROG = 24;
  public static final int LLAVEI = 6;
  public static final int BARRA = 18;
  public static final int LLAVEF = 7;
  public static final int FLECHA = 9;
  public static final int ERROR = 12;
  public static final int TILD = 11;
  public static final int Identificador = 10;
  public static final int DIGITU = 14;
  public static final int COMA = 23;
  public static final int SEPARADOR = 4;
  public static final int STRING = 5;
  public static final int ASTERISCO = 17;
  public static final int EOF = 0;
  public static final int SIMBOLO = 15;
  public static final int Reservadas = 3;
  public static final int error = 1;
  public static final int PARENTESISI = 19;
  public static final int PARENTESISF = 20;
  public static final int COMDOB = 26;
  public static final int LETRAU = 13;
  public static final int DPUNTOS = 8;
  public static final int MAS = 25;
  public static final int PTCOMA = 2;
}

